trigger:
  - master

pool:
  name: MyPool

jobs:
  - job: Job1
    displayName: 'Install Dependencies'
    steps:
      - checkout: self
        displayName: 'Checkout Code'

      - script: |
          echo "Installing Python 3.9 and necessary tools"
          choco install python --version 3.9 -y
          choco install googlechrome chromedriver -y
        displayName: 'Install Python & Chrome'

      - script: |
          python -m venv venv
          call .\venv\Scripts\activate && pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary robotframework-csvlibrary
        displayName: 'Install Robot Framework & Dependencies'

  - job: Job2
    displayName: 'Run Tests'
    steps:
      - script: |
          echo "Running tests"
          call .\venv\Scripts\activate && python -m robot --console verbose test/
        displayName: 'Run Robot Framework Test Cases'

      - script: |
          echo "Checking test directory and files..."
          dir test
        displayName: 'Debug: List Test Files'
