trigger:
  - master

pool:
  name: MyPool

jobs:
  - job: RunRobotTests
    displayName: 'Run Robot Framework Tests'
    strategy:
      parallel: 2  # Adjust the number based on available agents
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          addToPath: true

      - script: |
          echo "Setting up Python environment and installing dependencies..."
          python -m venv venv
          .\venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Set Up Python Environment'

      - script: |
          echo "Installing Chrome and ChromeDriver..."
          choco install googlechrome chromedriver -y
        displayName: 'Install Chrome & ChromeDriver'

      - script: |
          echo "Running Robot Framework tests in parallel..."
          .\venv\Scripts\activate
          pabot --processes 2 --outputdir Results test/
        displayName: 'Run Robot Framework Tests in Parallel'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Test Results'
        inputs:
          PathtoPublish: 'Results'
          ArtifactName: 'RobotFrameworkReports'
          publishLocation: 'Container'
        condition: succeededOrFailed()
