trigger:
  - master

pool:
  name: MyPool

steps:
  # Checkout the repository
  - checkout: self
    displayName: 'Checkout Code'

  # Install dependencies and set up virtual environment (skip Python installation)
  - script: |
      echo "Setting up virtual environment and installing dependencies"
      python -m venv venv
      call .\venv\Scripts\activate
      pip install --upgrade pip
      pip install robotframework robotframework-seleniumlibrary robotframework-csvlibrary robotframework-parallel
    displayName: 'Install Dependencies & Set Up Virtual Environment'

  # Install Google Chrome and ChromeDriver
  - script: |
      choco install googlechrome chromedriver -y
    displayName: 'Install Chrome & ChromeDriver'

  # Debug test directory (optional)
  - script: |
      echo "Checking test directory and files..."
      dir test
    displayName: 'Debug: List Test Files'

  # Run Robot Framework tests in parallel using robotframework-parallel
  - script: |
      echo "Running tests in parallel"
      call .\venv\Scripts\activate
      robot --console verbose --parallel 4 test/
    displayName: 'Run Robot Framework Tests in Parallel'
