trigger:
  - master

pool:
  name: MyPool

jobs:
  - job: RunTestsOnDevice1
    displayName: 'Run Tests on Device 1'
    steps:
      - checkout: self
        displayName: 'Checkout Code'

      - script: |
          echo "Installing Python 3.9 and necessary tools"
          choco install python --version 3.9 -y
          choco install googlechrome chromedriver -y
        displayName: 'Install Python & Chrome'

      - script: |
          python -m venv venv
          call .\venv\Scripts\activate && pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary robotframework-csvlibrary
        displayName: 'Install Robot Framework & Dependencies'

      - script: |
          echo "Running tests on Device 1"
          call .\venv\Scripts\activate && python -m robot --console verbose --variable DEVICE:Device1 test/
        displayName: 'Run Robot Framework Test Cases on Device 1'

  - job: RunTestsOnDevice2
    displayName: 'Run Tests on Device 2'
    steps:
      - checkout: self
        displayName: 'Checkout Code'

      - script: |
          echo "Installing Python 3.9 and necessary tools"
          choco install python --version 3.9 -y
          choco install googlechrome chromedriver -y
        displayName: 'Install Python & Chrome'

      - script: |
          python -m venv venv
          call .\venv\Scripts\activate && pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary robotframework-csvlibrary
        displayName: 'Install Robot Framework & Dependencies'

      - script: |
          echo "Running tests on Device 2"
          call .\venv\Scripts\activate && python -m robot --console verbose --variable DEVICE:Device2 test/
        displayName: 'Run Robot Framework Test Cases on Device 2'
