trigger:
  - master

pool:
  name: MyPool  # Replace with your agent pool name

jobs:
  - job: RunTestsParallel
    displayName: 'Run Tests on Two Devices in Parallel'
    steps:
      - checkout: self
        displayName: 'Checkout Code'

      - script: |
          echo "Installing Python 3.9"
          choco install python --version 3.9 -y
        displayName: 'Install Python'

      - script: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install --upgrade pip
          pip install robotframework robotframework-appiumlibrary
        displayName: 'Install Robot Framework & Appium Library'

      - script: |
          choco install googlechrome chromedriver -y
        displayName: 'Install Chrome & ChromeDriver'

      - script: |
          echo "Starting tests on Device 1..."
          start cmd /c ".\venv\Scripts\python -m robot --variable DEVICE_NAME:Device1 test/"

          echo "Starting tests on Device 2..."
          start cmd /c ".\venv\Scripts\python -m robot --variable DEVICE_NAME:Device2 test/"

          echo "Waiting for tests to complete..."
          timeout /T 30
        displayName: 'Run Tests on Both Devices in Parallel'
