trigger:
  - master

pool:
  name: MyPool  

jobs:
  - job: Setup
    displayName: "Setup Environment"
    steps:
      - checkout: self
        displayName: "Checkout Code"

      - script: |
          echo "Installing Python 3.9..."
          choco install python --version 3.9 -y
        displayName: "Install Python"

      - script: |
          echo "Installing Dependencies..."
          python -m venv venv
          .\venv\Scripts\activate && pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary robotframework-csvlibrary pabot
        displayName: "Install Robot Framework & Dependencies"

      - script: |
          echo "Installing Chrome & ChromeDriver..."
          choco install googlechrome chromedriver -y
        displayName: "Install Chrome & ChromeDriver"

  - job: RunTests
    displayName: "Run Robot Framework Tests"
    dependsOn: Setup
    steps:
      - script: |
          echo "Running Tests in Parallel..."
          .\venv\Scripts\activate && pabot --processes 4 --outputdir results test/
        displayName: "Run Tests with Pabot (Parallel Execution)"

      - script: |
          echo "Listing Test Results..."
          dir results
        displayName: "Debug: List Test Results"
