trigger:
  - master

pool:
  name: MyPool  

jobs:
  - job: Setup
    displayName: "Setup Environment"
    steps:
      - checkout: self
        displayName: "Checkout Code"

      - script: |
          echo "Installing Python 3.9..."
          choco install python --version 3.9 -y
        displayName: "Install Python"

      - script: |
          echo "Setting up Virtual Environment..."
          python -m venv venv
          echo "Installing Dependencies..."
          .\venv\Scripts\activate && python -m pip install --no-cache-dir robotframework robotframework-seleniumlibrary robotframework-csvlibrary pabot
        displayName: "Setup Virtual Environment & Install Dependencies"

      - script: |
          echo "Installing Chrome & ChromeDriver..."
          choco install googlechrome chromedriver -y
        displayName: "Install Chrome & ChromeDriver"

  - job: RunTests
    displayName: "Run Robot Framework Tests"
    dependsOn: Setup
    steps:
      - script: |
          echo "Running Tests in Parallel..."
          .\venv\Scripts\activate && pabot --processes 4 --outputdir results test/
        displayName: "Run Tests with Pabot (Parallel Execution)"

      - script: |
          echo "Listing Test Results..."
          dir results
        displayName: "Debug: List Test Results"
