trigger:
  - master

pool:
  name: MyPool

jobs:
  - job: InstallDependencies
    displayName: 'Install Dependencies'
    pool:
      name: MyPool
    steps:
      - checkout: self
        displayName: 'Checkout Code'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          addToPath: true
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install Python Dependencies'

  - job: RunTests
    displayName: 'Run Robot Framework Tests'
    dependsOn: []
    pool:
      name: MyPool
    steps:
      - script: |
          robot -d Results Tests/
        displayName: 'Run Robot Framework Tests'
        continueOnError: true
