trigger:
  - master

pool:
  name: MyPool  

jobs:
- job: Setup
  displayName: 'Setup Environment'
  steps:
    - checkout: self
      displayName: 'Checkout Code'

    - script: |
        echo "Installing Python 3.9"
        choco install python --version=3.9 -y
      displayName: 'Install Python'

    - script: |
        python -m venv venv
        venv\Scripts\python -m pip install --upgrade pip
        venv\Scripts\pip install -r requirements.txt
        echo "Checking venv directory after creation..."
        dir venv
      displayName: 'Create and Verify Virtual Environment'

    - script: |
        choco install googlechrome -y
        venv\Scripts\pip install webdriver-manager
        venv\Scripts\python -m webdriver_manager.chrome
      displayName: 'Install Chrome & ChromeDriver'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'venv'
        artifactName: 'venv'
      displayName: 'Save venv for later jobs'

- job: RunTests
  displayName: 'Execute Robot Framework Tests'
  dependsOn: Setup
  steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'venv'
        downloadPath: '.'
      displayName: 'Restore venv'

    - script: |
        echo "Checking venv directory before running tests..."
        dir venv
      displayName: 'Debug: Check venv Directory Before Running Tests'

    - script: |
        echo "Running Robot Framework tests..."
        venv\Scripts\python -m robot --console verbose --outputdir results test/
      displayName: 'Run Robot Framework Tests'
