trigger:
  - master

pool:
  name: MyPool  

jobs:
- job: Setup
  displayName: 'Setup Environment'
  steps:
    - checkout: self
      displayName: 'Checkout Code'

    - script: |
        echo "Installing Python 3.9"
        choco install python --version=3.9 -y
      displayName: 'Install Python'

    - script: |
        echo "Cleaning up the workspace..."
        del /f /q $(Build.SourcesDirectory)\venv
      displayName: 'Clean Up Workspace'

    - script: |
        echo "Creating virtual environment..."
        python -m venv $(Build.SourcesDirectory)\venv
        echo "Checking if virtual environment is created..."
        if exist $(Build.SourcesDirectory)\venv (
          echo "venv directory exists!"
        ) else (
          echo "venv directory does not exist!"
        )
        dir $(Build.SourcesDirectory)\venv
      displayName: 'Debug: Check venv Directory'

    - script: |
        echo "Upgrading pip and installing dependencies..."
        "$(Build.SourcesDirectory)\venv\Scripts\python" -m pip install --upgrade pip
        "$(Build.SourcesDirectory)\venv\Scripts\pip" install -r requirements.txt
      displayName: 'Install Dependencies'

    - script: |
        choco install googlechrome -y
        "$(Build.SourcesDirectory)\venv\Scripts\pip" install webdriver-manager
        "$(Build.SourcesDirectory)\venv\Scripts\python" -m webdriver_manager.chrome
      displayName: 'Install Chrome & ChromeDriver'

    - script: |
        echo "Checking test directory and files..."
        dir $(Build.SourcesDirectory)\test
      displayName: 'Debug: List Test Files'

- job: RunTests
  displayName: 'Execute Robot Framework Tests'
  dependsOn: Setup
  steps:
    - script: |
        echo "Running Robot Framework tests..."
        "$(Build.SourcesDirectory)\venv\Scripts\python" -m robot --console verbose --outputdir results $(Build.SourcesDirectory)\test/
      displayName: 'Run Robot Framework Tests'

- job: RunTestsParallel
  displayName: 'Execute Tests in Parallel'
  dependsOn: Setup
  steps:
    - script: |
        echo "Running tests in parallel..."
        "$(Build.SourcesDirectory)\venv\Scripts\pip" install robotframework-pabot
        "$(Build.SourcesDirectory)\venv\Scripts\python" -m pabot --processes 4 --outputdir results $(Build.SourcesDirectory)\test/
      displayName: 'Run Tests in Parallel'
