trigger:
  - master

pool:
  name: MyPool  # Replace with your agent pool name

jobs:
  - job: InstallDependencies
    displayName: 'Install Dependencies'
    steps:
      - checkout: self
        displayName: 'Checkout Code'

      - script: |
          echo "Installing Python 3.9"
          choco install python --version 3.9 -y
        displayName: 'Install Python'

      - script: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary robotframework-csvlibrary
        displayName: 'Install Robot Framework & Dependencies'

      - script: |
          choco install googlechrome chromedriver -y
        displayName: 'Install Chrome & ChromeDriver'

  - job: RunTests
    displayName: 'Run Robot Framework Tests'
    dependsOn: InstallDependencies
    steps:
      - checkout: self
        displayName: 'Checkout Code'

      - script: |
          echo "Checking test directory and files..."
          dir test
        displayName: 'Debug: List Test Files'

      - script: |
          echo "Activating virtual environment and running tests..."
          .\venv\Scripts\activate
          python -m robot --console verbose test/
        displayName: 'Run All Robot Framework Test Cases'
