trigger:
  - master

pool:
  name: MyPool

steps:
  - checkout: self
    displayName: 'Checkout Code'

  - script: |
      echo "Setting up Python environment"
      python -m venv venv
      .\venv\Scripts\activate
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Set Up Python Environment'

  - script: |
      echo "Installing Robot Framework and dependencies"
      pip install robotframework
      pip install robotframework-seleniumlibrary
      pip install robotframework-csvlibrary
    displayName: 'Install Robot Framework & Dependencies'

  - script: |
      echo "Installing Chrome and ChromeDriver"
      choco install googlechrome chromedriver -y
    displayName: 'Install Chrome & ChromeDriver'

  - script: |
      echo "Running Robot Framework tests"
      .\venv\Scripts\activate
      robot -d Results test/
    displayName: 'Run Robot Framework Tests'
