trigger:
  - master

pool:
  name: MyPool

steps:
  - checkout: self
    displayName: 'Checkout Code'

  - script: |
      echo "Installing Python 3.9"
      choco install python --version 3.9 -y
    displayName: 'Install Python'

  - script: |
      echo "Setting up virtual environment and installing dependencies"
      python -m venv venv
      call .\venv\Scripts\activate
      pip install --upgrade pip
      pip install robotframework
      pip install robotframework-seleniumlibrary
      pip install robotframework-csvlibrary
      pip install pabot
    displayName: 'Install Dependencies & Set Up Virtual Environment'

  - script: |
      echo "Running tests in parallel with Pabot"
      call .\venv\Scripts\activate
      pabot --processes 4 test/
    displayName: 'Run Robot Framework Tests in Parallel'
